service: twitter-bot

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false

functions:
  mimin:
    handler: handler.mimin
    events:
      - http:
          path: endpoint
          method: get
#    environment:
#      variable2: value2
