service: twitter-bot-mimin

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/mimin/*"]]

functions:
  main:
    handler: handler.main
    description: Post image to twitter when niltea is push to github
    events:
      - http:
          path: endpoint
          method: post
    environment:
      MIMIN_CONSUMER_KEY:        ${file(kms.js):kms.MIMIN_CONSUMER_KEY}
      MIMIN_CONSUMER_SECRET:     ${file(kms.js):kms.MIMIN_CONSUMER_SECRET}
      MIMIN_ACCESS_TOKEN_KEY:    ${file(kms.js):kms.MIMIN_ACCESS_TOKEN_KEY}
      MIMIN_ACCESS_TOKEN_SECRET: ${file(kms.js):kms.MIMIN_ACCESS_TOKEN_SECRET}

resources:
  Description: Post image to twitter when niltea is push to github
  Resources:
    MainLogGroup:
      Properties:
        RetentionInDays: 7
