service: twitter-bot-mimin

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/mimin/*"]]

functions:
  main:
    handler: handler.main
    description: Post image to twitter when niltea is push to github
    environment:
      MIMIN_TWITTER_COMSUMER_KEY:        "${ssm:/mimin/consumer_key~true}"
      MIMIN_TWITTER_COMSUMER_SECRET:     "${ssm:/mimin/consumer_secret~true}"
      MIMIN_TWITTER_ACCESS_TOKEN:        "${ssm:/mimin/access_token_key~true}"
      MIMIN_TWITTER_ACCESS_TOKEN_SECRET: "${ssm:/mimin/access_token_secret~true}"
    events:
      - http:
          path: endpoint
          method: post

resources:
  Description: Post image to twitter when niltea is push to github
  Resources:
    MainLogGroup:
      Properties:
        RetentionInDays: 7
